spring.application.name=job4j_social_media_api

spring.config.import=optional:file:./dev/dev.properties

socialMedia.openapi.dev-url=http://localhost:8080
socialMedia.openapi.prod-url=https://mydomen.com
springdoc.swagger-ui.tryItOutEnabled=true

#FUCKINGSHIT
jwt.token.secret=easehjkopyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJzdHVkZW50X2pvYjRqIiwiaWF0Ijox
jwt.token.expired=3600000
server.port=8080
